### ISSUE TITLE
Your license is funny

### ISSUE THREAD

**Issue by xmj** [marklap/rundeckrun#23]
Hi there,

CC-BY-SA is heavily disreputed for using with software projects. It's fine for text, books, and documentation, but using it with code just generates headaches.

Could you please change it to some permissive license, like BSD, MIT, ISC, or a weak copyleft license like the Apache License 2.0 ?

**Comment by marklap** [comment]
Fair point. I'll switch it over to Apache 2.0 shortly.

**Comment by marklap** [comment]
Version 0.1.13 sports the Apache 2.0 license.

**Comment by xmj** [comment]
THANK YOU!!!
