### ISSUE TITLE
jobs failing on ec2 nodes

### ISSUE THREAD

**Issue by nicolas-g** [marklap/rundeckrun#25]
I'm using rundeckrun to execute various jobs on physical servers with no problem. However when I try to execute the same jobs on an ec2 node suing the rundeck ec2 plugin it's failing .

If I execute the jobs from the Rundeck UI there are no issues, the problem is only when I execute the jobs on ec2 nodes from rundeckrun.

The rundeckrun output from my script is always the same when failing or not :
```
/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

This is what I see from the UI Log output : 
```
21:23:52	rundeck.example.com		com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={hostname=server1.example.com, dominant=true, }}
21:23:52				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:333)
21:23:52				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:85)
21:23:52				at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:124)
21:23:52				at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
21:23:53			Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={hostname=server1.example.com, dominant=true, }}
21:23:53			No matched nodes: NodeSet{includes={hostname=server1.example.com, dominant=true, }}
```

The above error is the same for any kind of job I run on any ec2 node.

Rundeckrun = 0.1.15
requests = 2.7.0
Rundeck server = 2.4.0-1

**Comment by marklap** [comment]
The python output is a warning not an *error*. If you accept the risks in communicating with a server (Rundeck) that has an invalid certificate (as far as the client, rundeckrun/requests is concerned), then you can ignore that warning.

If I were to guess as to the source of the problem from the UI log output, I'd say the node filter you're supplying to rundeckrun is not the same as the node filter you're using in the UI.

**Comment by marklap** [comment]
Let me know if you're still having trouble and if I can help. I'll leave this issue open a bit longer before I close it out.

**Comment by nicolas-g** [comment]
I'v manage to make it work by using the name argument instead of hostname. 

Thanks for your help.

**Comment by marklap** [comment]
Excellent
