### ISSUE TITLE
Tests are installed in top-level site-packages directory

### ISSUE THREAD

**Issue by zyv** [marklap/rundeckrun#28]
Hi Mark,

Unfortunately, when rundeckrun is installed, tests are installed as well as a top-level tests package in site-packages. It's better to not to take such a generic package name in order to avoid conflicts.

I can see two different solutions to this:

1) one possibility is to move tests inside rundeckrun namespace
2) another possibility is leave tests the way they are, and simply not install them

I could try to come up with a pull request if you want, but then I'd need to know which solution you would prefer...

Many thanks!

**Comment by marklap** [comment]
Yuck. Didn't realize that was happening. I'm always open to suggestions but my gut is saying they shouldn't be installed in site-packages at all.

**Comment by zyv** [comment]
>  I'm always open to suggestions but my gut is saying they shouldn't be installed in site-packages at all.

Well, in this case, the solution would be quite a straightforward one: just exclude the top-level `tests` package and all of its subpackages (if there will be some at any point in time): #29 .

I have no preference one way or another, there are valid arguments for keeping tests inside your source package, and likewise for keeping them separate [*]. I guess some authors decide to keep tests inside their package and ship it with the source distribution, because they want users to be able to run tests after the package has been installed to validate the environment, like e.g. NumPy / SciPy. Probably, for rundeckrun it doesn't make much sense, especially since the tests currently require a test Rundeck instance... 

[*]: https://pytest.org/latest/goodpractises.html

But it's up to you :) my only worry is top-level namespace pollution, which can be easily avoided either way.

**Comment by marklap** [comment]
This is pushed up as 0.2.1. Thanks again @zyv

**Comment by zyv** [comment]
Thanks Mark, your work is very much appreciated; using rundeckrun instead of hacking something up myself saved me a lot of time! Tested both issues today, and seems to work fine now :+1:

**Comment by marklap** [comment]
Beautiful. Thanks for helping out.
