### ISSUE TITLE
rd.get_execution_output returns Attribute error

### ISSUE THREAD

**Issue by mikkyornyx** [marklap/rundeckrun#30]
After executing a job and running rd.get_execution_output(job_id) command, I get python Attribute error as shown below:

>>> rd.get_execution_output('30')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rundeck/client.py", line 656, in get_execution_output
    return results._as_dict_method(results)
AttributeError: 'dict' object has no attribute '_as_dict_method'

Running the same job without trying to serialize output to json (e.g. having "raw" option enabled) works fine (output attached)

[rundeck_output.txt](https://github.com/marklap/rundeckrun/files/102030/rundeck_output.txt)

**Comment by marklap** [comment]
Thanks for creating an issue. I'll take a look this week.

**Comment by marklap** [comment]
Resloved with 9f38f4014603e36c9d7b5e1c679482e66b23aa11
