### ISSUE TITLE
Feature request : Need one call to delete older job execution

### ISSUE THREAD

**Issue by leoprincep** [marklap/rundeckrun#31]
Currently we can list older job executions but no call to delete them.. Yeah, we can pass the execution IDs to http API urls and can invoke with curl but would have been nicer if we have rundeckrun call to remove old executions with execution id as arg.

**Comment by marklap** [comment]
Deleting executions wasn't made available until version 12 of the Rundeck API (Rundeck version =>2.2.0). Rundeckrun currently supports version 11 of the Rundeck API. While I'm not in a position to sink a significant amount of time into upgrading this library, I'm more than happy to review and accept Pull Requests.
